name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      FC: gfortran
      GCC_V: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt install -y gfortran-${GCC_V} cmake numdiff wget python-dev python build-essential
        wget -P . "https://bootstrap.pypa.io/get-pip.py" && sudo python get-pip.py && rm get-pip.py
        sudo pip install ford
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} 100

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j $(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: miniFAVOR Documenation
      run: |
        cd doc
        ford miniFAVOR-FORD-file.md

    - name: Save HTML Documentation
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: doc/miniFAVOR-doc
        if-no-files-found: error
